stage_writeup:
  description: >
    Write a narrative prose for these events in the storyline:
    
    
    {stage_events}
    

  expected_output: >
    A narrative prose for the story chapter covering these events:


    {stage_events}

  agent: creative_writer

expand_events:
  description: >
    Expand these events in this story chapter:

    
    {stage_events}


    Add more details to the scenes, including character thoughts, emotions, and reactions.
    
  expected_output: >
    A detailed description of how the story presents the events in this story chapter.
    It should include details about backstory, character motivations, and the consequences of the events.

  agent: creative_writer

