draft_plot:
  description: >
    Draft a plot outline for the story.
    The story should have the following characters:

    {characters}

  expected_output: >
    An detailed outline of the story plot describing what characters do, their motivations
    the specific challenges they face, the settings, the emotions, the conflicts, and the resolutions.
  agent: creative_writer
